exports.main = {
	"ret": 0,
	"desc": "ok",
	"data": {
		"collections": [{
			"name": "addresses"
		}, {
			"name": "ads"
		}, {
			"name": "carts"
		}, {
			"name": "documents"
		}, {
			"name": "goods"
		}, {
			"name": "goods_activities"
		}, {
			"name": "goods_categories"
		}, {
			"name": "goods_day_sales"
		}, {
			"name": "goods_deletes"
		}, {
			"name": "goods_shop_day_sales"
		}, {
			"name": "goods_visites"
		}, {
			"name": "identity"
		}, {
			"name": "order_refunds"
		}, {
			"name": "orders"
		}, {
			"name": "shop_categories"
		}, {
			"name": "shop_comments"
		}, {
			"name": "shops"
		}, {
			"name": "user_balance_logs"
		}, {
			"name": "user_often_buy_shops"
		}, {
			"name": "user_recommend_shops"
		}, {
			"name": "users"
		}]
	}
}
